// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: calc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CalcService_AddNumbers_FullMethodName    = "/calc.CalcService/AddNumbers"
	CalcService_PrimeNumbers_FullMethodName  = "/calc.CalcService/PrimeNumbers"
	CalcService_AvgNumbers_FullMethodName    = "/calc.CalcService/AvgNumbers"
	CalcService_StreamNumbers_FullMethodName = "/calc.CalcService/StreamNumbers"
	CalcService_Sqrt_FullMethodName          = "/calc.CalcService/Sqrt"
)

// CalcServiceClient is the client API for CalcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalcServiceClient interface {
	AddNumbers(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	PrimeNumbers(ctx context.Context, in *PrimeNRequest, opts ...grpc.CallOption) (CalcService_PrimeNumbersClient, error)
	AvgNumbers(ctx context.Context, opts ...grpc.CallOption) (CalcService_AvgNumbersClient, error)
	StreamNumbers(ctx context.Context, opts ...grpc.CallOption) (CalcService_StreamNumbersClient, error)
	Sqrt(ctx context.Context, in *SqrtRequest, opts ...grpc.CallOption) (*SqrtResponse, error)
}

type calcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcServiceClient(cc grpc.ClientConnInterface) CalcServiceClient {
	return &calcServiceClient{cc}
}

func (c *calcServiceClient) AddNumbers(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, CalcService_AddNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcServiceClient) PrimeNumbers(ctx context.Context, in *PrimeNRequest, opts ...grpc.CallOption) (CalcService_PrimeNumbersClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalcService_ServiceDesc.Streams[0], CalcService_PrimeNumbers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &calcServicePrimeNumbersClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalcService_PrimeNumbersClient interface {
	Recv() (*PrimeNResponse, error)
	grpc.ClientStream
}

type calcServicePrimeNumbersClient struct {
	grpc.ClientStream
}

func (x *calcServicePrimeNumbersClient) Recv() (*PrimeNResponse, error) {
	m := new(PrimeNResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calcServiceClient) AvgNumbers(ctx context.Context, opts ...grpc.CallOption) (CalcService_AvgNumbersClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalcService_ServiceDesc.Streams[1], CalcService_AvgNumbers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &calcServiceAvgNumbersClient{ClientStream: stream}
	return x, nil
}

type CalcService_AvgNumbersClient interface {
	Send(*AvgNRequest) error
	CloseAndRecv() (*AvgResponse, error)
	grpc.ClientStream
}

type calcServiceAvgNumbersClient struct {
	grpc.ClientStream
}

func (x *calcServiceAvgNumbersClient) Send(m *AvgNRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calcServiceAvgNumbersClient) CloseAndRecv() (*AvgResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AvgResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calcServiceClient) StreamNumbers(ctx context.Context, opts ...grpc.CallOption) (CalcService_StreamNumbersClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalcService_ServiceDesc.Streams[2], CalcService_StreamNumbers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &calcServiceStreamNumbersClient{ClientStream: stream}
	return x, nil
}

type CalcService_StreamNumbersClient interface {
	Send(*StreamNRequest) error
	Recv() (*StreamNResponse, error)
	grpc.ClientStream
}

type calcServiceStreamNumbersClient struct {
	grpc.ClientStream
}

func (x *calcServiceStreamNumbersClient) Send(m *StreamNRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calcServiceStreamNumbersClient) Recv() (*StreamNResponse, error) {
	m := new(StreamNResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calcServiceClient) Sqrt(ctx context.Context, in *SqrtRequest, opts ...grpc.CallOption) (*SqrtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqrtResponse)
	err := c.cc.Invoke(ctx, CalcService_Sqrt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalcServiceServer is the server API for CalcService service.
// All implementations must embed UnimplementedCalcServiceServer
// for forward compatibility
type CalcServiceServer interface {
	AddNumbers(context.Context, *SumRequest) (*SumResponse, error)
	PrimeNumbers(*PrimeNRequest, CalcService_PrimeNumbersServer) error
	AvgNumbers(CalcService_AvgNumbersServer) error
	StreamNumbers(CalcService_StreamNumbersServer) error
	Sqrt(context.Context, *SqrtRequest) (*SqrtResponse, error)
	mustEmbedUnimplementedCalcServiceServer()
}

// UnimplementedCalcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalcServiceServer struct {
}

func (UnimplementedCalcServiceServer) AddNumbers(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNumbers not implemented")
}
func (UnimplementedCalcServiceServer) PrimeNumbers(*PrimeNRequest, CalcService_PrimeNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumbers not implemented")
}
func (UnimplementedCalcServiceServer) AvgNumbers(CalcService_AvgNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method AvgNumbers not implemented")
}
func (UnimplementedCalcServiceServer) StreamNumbers(CalcService_StreamNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamNumbers not implemented")
}
func (UnimplementedCalcServiceServer) Sqrt(context.Context, *SqrtRequest) (*SqrtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sqrt not implemented")
}
func (UnimplementedCalcServiceServer) mustEmbedUnimplementedCalcServiceServer() {}

// UnsafeCalcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalcServiceServer will
// result in compilation errors.
type UnsafeCalcServiceServer interface {
	mustEmbedUnimplementedCalcServiceServer()
}

func RegisterCalcServiceServer(s grpc.ServiceRegistrar, srv CalcServiceServer) {
	s.RegisterService(&CalcService_ServiceDesc, srv)
}

func _CalcService_AddNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServiceServer).AddNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalcService_AddNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServiceServer).AddNumbers(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalcService_PrimeNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalcServiceServer).PrimeNumbers(m, &calcServicePrimeNumbersServer{ServerStream: stream})
}

type CalcService_PrimeNumbersServer interface {
	Send(*PrimeNResponse) error
	grpc.ServerStream
}

type calcServicePrimeNumbersServer struct {
	grpc.ServerStream
}

func (x *calcServicePrimeNumbersServer) Send(m *PrimeNResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalcService_AvgNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalcServiceServer).AvgNumbers(&calcServiceAvgNumbersServer{ServerStream: stream})
}

type CalcService_AvgNumbersServer interface {
	SendAndClose(*AvgResponse) error
	Recv() (*AvgNRequest, error)
	grpc.ServerStream
}

type calcServiceAvgNumbersServer struct {
	grpc.ServerStream
}

func (x *calcServiceAvgNumbersServer) SendAndClose(m *AvgResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calcServiceAvgNumbersServer) Recv() (*AvgNRequest, error) {
	m := new(AvgNRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalcService_StreamNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalcServiceServer).StreamNumbers(&calcServiceStreamNumbersServer{ServerStream: stream})
}

type CalcService_StreamNumbersServer interface {
	Send(*StreamNResponse) error
	Recv() (*StreamNRequest, error)
	grpc.ServerStream
}

type calcServiceStreamNumbersServer struct {
	grpc.ServerStream
}

func (x *calcServiceStreamNumbersServer) Send(m *StreamNResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calcServiceStreamNumbersServer) Recv() (*StreamNRequest, error) {
	m := new(StreamNRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalcService_Sqrt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqrtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServiceServer).Sqrt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalcService_Sqrt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServiceServer).Sqrt(ctx, req.(*SqrtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalcService_ServiceDesc is the grpc.ServiceDesc for CalcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calc.CalcService",
	HandlerType: (*CalcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNumbers",
			Handler:    _CalcService_AddNumbers_Handler,
		},
		{
			MethodName: "Sqrt",
			Handler:    _CalcService_Sqrt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumbers",
			Handler:       _CalcService_PrimeNumbers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AvgNumbers",
			Handler:       _CalcService_AvgNumbers_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamNumbers",
			Handler:       _CalcService_StreamNumbers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calc.proto",
}
